include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Test.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

test:
  before_script:
    - mkdir -p ./build/client
    - echo "export const getMetaTags = () => []; export const prerenderMetaTags = () => '';" > ./build/client/metaData.js
  services:
    - redis:latest

spotbugs-sast:
  services:
    - redis:latest

pages:
  image: openjdk:16-jdk
  stage: deploy
  script:
    - ./gradlew dokkaHtml
    - rm -rf public
    - mv build/dokka/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
