include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Test.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

build:
  variables:
    AUTO_DEVOPS_BUILDX_INSTANCE_EXTRA_ARGS: "--driver=docker-container --platform=linux/amd64,linux/arm64/v8 --foobar"
    AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--platform=linux/amd64,linux/arm64/v8 --foobaz"
  before_script:
    - CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE
    - apk add git
    - git describe --always > server_version.txt
  artifacts:
    paths:
      - build

test:
  services:
    - redis:latest
  artifacts:
    paths:
      - build

spotbugs-sast:
  services:
    - redis:latest

pages:
  image: openjdk:16-jdk
  stage: deploy
  script:
    - ./gradlew dokkaHtml
    - rm -rf public
    - mv build/dokka/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
