package io.ontola.empathy.web

import io.ontola.rdf.hextuples.Hextuple
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertTrue

val hex = """
{
   "https://argu.co/info":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info"
      },
      "http://schema.org/name":[
         {
            "type":"p",
            "v":"Argu - Beslis samen beter",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "http://schema.org/description":[
         {
            "type":"p",
            "v":"Argu is een gebruiksklaar participatieplatform voor iedere organisatie. Betrek meer burgers, bouw een community en beslis beter.  Vraag vrijblijvend een demo aan.",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://ns.ontola.io/core#coverPhoto":[
         {
            "type":"p",
            "v":"https://argu.co/info#CoverImage",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#header":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://argu.co/ns/sales#header>",
            "dt":"localId"
         }
      ],
      "https://argu.co/ns/sales#callToActionBlock":[
         {
            "type":"p",
            "v":"https://argu.co/info#CTABlock",
            "dt":"globalId"
         }
      ],
      "https://ns.ontola.io/core#navigationsMenu":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>",
            "dt":"localId"
         }
      ],
      "https://argu.co/ns/sales#showcase":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://argu.co/ns/sales#showcase>",
            "dt":"localId"
         }
      ],
      "https://argu.co/ns/sales#cases":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://argu.co/ns/sales#cases>",
            "dt":"localId"
         }
      ],
      "https://argu.co/ns/sales#propositions":[
         {
            "type":"p",
            "v":"https://argu.co/info#propositions",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#duoBlock":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://argu.co/ns/sales#duoBlock>",
            "dt":"localId"
         }
      ],
      "https://argu.co/ns/sales#blogs":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://argu.co/ns/sales#blogs>",
            "dt":"localId"
         }
      ]
   },
   "https://argu.co/info.<https://argu.co/ns/sales#header>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://argu.co/ns/sales#header>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://argu.co/ns/sales#Header",
            "dt":"globalId"
         }
      ],
      "http://schema.org/name":[
         {
            "type":"p",
            "v":"Beslis samen beter",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "http://schema.org/text":[
         {
            "type":"p",
            "v":"Wij helpen jou om je doelgroep te betrekken. Simpel, interactief en toegankelijk.",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://argu.co/ns/sales#buttonLink":[
         {
            "type":"p",
            "v":"https://calendly.com/argu_co/online-demo",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#buttonText":[
         {
            "type":"p",
            "v":"Plan een demo",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://argu.co/ns/sales#backgroundImage":[
         {
            "type":"p",
            "v":"https://dptr8y9slmfgv.cloudfront.net/sales/images/header.svg",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#backgroundImageMobile":[
         {
            "type":"p",
            "v":"https://dptr8y9slmfgv.cloudfront.net/sales/images/header_mobile.svg",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#backgroundImageXL":[
         {
            "type":"p",
            "v":"https://dptr8y9slmfgv.cloudfront.net/sales/images/header_xl.svg",
            "dt":"globalId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://ns.ontola.io/core#MenuItem",
            "dt":"globalId"
         }
      ],
      "https://argu.co/ns/sales#callToAction":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://argu.co/ns/sales#callToAction>",
            "dt":"localId"
         }
      ],
      "https://ns.ontola.io/core#menuItems":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>",
            "dt":"localId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://argu.co/ns/sales#callToAction>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://argu.co/ns/sales#callToAction>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://argu.co/ns/sales#CallToActionButton",
            "dt":"globalId"
         }
      ],
      "http://schema.org/text":[
         {
            "type":"p",
            "v":"Plan een demo",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://ns.ontola.io/core#href":[
         {
            "type":"p",
            "v":"https://calendly.com/argu_co/online-demo",
            "dt":"globalId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq",
            "dt":"globalId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_0":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_1":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_2":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_2>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_3":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_3>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_4":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_4>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_5":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_5>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_6":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_6>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_7":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_7>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_8":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_8>",
            "dt":"localId"
         }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#_9":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_9>",
            "dt":"localId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://ns.ontola.io/core#MenuItem",
            "dt":"globalId"
         }
      ],
      "http://schema.org/image":[
         {
            "type":"p",
            "v":"_:https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>.<http://schema.org/image>",
            "dt":"localId"
         }
      ],
      "http://schema.org/isPartOf":[
         {
            "type":"p",
            "v":"https://argu.co/info",
            "dt":"globalId"
         }
      ],
      "http://schema.org/name":[
         {
            "type":"p",
            "v":"Argu",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://ns.ontola.io/core#href":[
         {
            "type":"p",
            "v":"https://argu.co/info",
            "dt":"globalId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>.<http://schema.org/image>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_0>.<http://schema.org/image>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://ns.ontola.io/core#PictureSet",
            "dt":"globalId"
         }
      ],
      "https://ns.ontola.io/core#ariaLabel":[
         {
            "type":"p",
            "v":"Logo",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://ns.ontola.io/core#format/svg":[
         {
            "type":"p",
            "v":"https://dptr8y9slmfgv.cloudfront.net/sales/images/argu-logo.svg",
            "dt":"globalId"
         }
      ],
      "https://ns.ontola.io/core#format/png":[
         {
            "type":"p",
            "v":"https://dptr8y9slmfgv.cloudfront.net/sales/images/argu-logo.png",
            "dt":"globalId"
         }
      ]
   },
   "https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>":{
      "_id":{
         "type":"id",
         "v":"https://argu.co/info.<https://ns.ontola.io/core#navigationsMenu>.<https://ns.ontola.io/core#menuItems>.<http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>"
      },
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#type":[
         {
            "type":"p",
            "v":"https://ns.ontola.io/core#MenuItem",
            "dt":"globalId"
         }
      ],
      "http://schema.org/name":[
         {
            "type":"p",
            "v":"Functionaliteiten",
            "dt":"http://www.w3.org/2001/XMLSchema#string"
         }
      ],
      "https://ns.ontola.io/core#href":[
         {
            "type":"p",
            "v":"https://argu.co/info/functionaliteiten",
            "dt":"globalId"
         }
      ]
   }
}
""".trimIndent()

class SeedTest {
    @Test
    fun testToSliceWorksOnEmptyList() {
        val result = emptyList<Hextuple>().toSlice()

        assertTrue(result.isEmpty())
    }

    @Test
    fun testToSlice() {
        val result = Json.decodeFromString<DataSlice>(hex)

        assertTrue(!result.isEmpty())
    }
}
